### ISSUE TITLE
Syntax error, unexpected token "match" on PHP 8.0

### ISSUE THREAD

**Issue by mzurawek** [T-Regx/T-Regx#87]
**Description**

Using
`Pattern::pcre($string)->match($sub) `
produces syntax error. This is probably due to new keyword "match" used on PHP 8.0

**To Reproduce**

`Use Pattern::pcre($string)->match($sub)`
 on PHP 8.0

<img width="892" alt="Screenshot 2020-11-27 at 17 54 36" src="https://user-images.githubusercontent.com/25429435/100474729-94f82f80-30e1-11eb-8b18-c2c73f8a1133.png">

**Comment by Danon** [comment]
Oh, thank you very much for taking interest! 👍 

Yes, it indeed is because of `match` keyword in PHP8. The fix is already on it's way, you can see `php8` branch in https://travis-ci.org/github/T-Regx/T-Regx/branches and it works well so far. You can include `dev-develop` or `dev-php8` in your composer.json, if you wish to run T-Regx on PHP8.

The new version, 0.10.0 should include the changes - most notably rename of `Match` to `Detail`, to support php8 (changes described in [ChangeLog.md](https://github.com/T-Regx/T-Regx/blob/develop/ChangeLog.md)). For a while we'll support both 0.9 (php 7.1+) and 0.10 (php 8).

Currently, 0.9.12 supports both `Match` and `Detail`, to allow people to migrate, but any form of backwards compatibility on PHP 8 will be broken (we can't even provide a class for PHP 7.1-7.4 users, because that very same code would be run on PHP8 breaking it).

So either use `dev-develop`/`dev-php8` in your `composer.json` or wait for the new release which should be in 3-10 days :) 

Thank you very much for raising an issue! It's great to hear from you. Please don't hesitate if you have any questions, big or small.

**Comment by Danon** [comment]
https://github.com/T-Regx/T-Regx/releases/tag/v0.10.0

Yea, it took a little longer than 3-10 days :D I'm sorry about that.
